# Includes a postgres and a fastapi service

services:
  fastapi:
    build: .
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@postgres/microblog
      - MICROBLOG_ADMIN_PASSWORD=password
    command: sh -c "alembic upgrade head && uvicorn microblog.app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: microblog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"